# Generated by Django 4.2 on 2024-02-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meetups", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetup",
            name="date",
            field=models.DateField(default="2021-04-12"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="meetup",
            name="organizer_email",
            field=models.EmailField(default="", max_length=254),
            preserve_default=False,
        ),
    ]
