[tool.ruff]
lint.extend-select = [
  "ANN",
  "C4",
  "COM",
  "I",
  "N",
  "PT",
  "RET",
  "SIM",
  "TCH",
  "TID",
]
lint.ignore = ["ANN002", "ANN003", "ANN101", "ANN102", "COM812"]
show-fixes = true
line-length = 120

[tool.ruff.lint.isort]
case-sensitive = true

[tool.djlint]
indent = 2
line_break_after_multiline_tag = true
preserve_blank_lines = true
